[platformio]
default_envs = esp32dev
src_dir = firmware/src
include_dir = firmware/include

[env:esp32dev]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino

platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.2
    framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.2/esp32-arduino-libs-3.0.2.zip

monitor_speed = 115200